language: node_js
node_js:
  - iojs
  - '0.10'

env:
  global:
    - secure: HmsnQqfaOjZ6HJfursQUvqVRlUN2H1ICwDZXJH6rqSgZi2olA6NT5CCitUG1V+4ksMBIpgT/ELR38OQN82BfWzFIQxLph5BcNYtOcKv+TU49m94hkfB4PXXbM1PhfJlHvuCMqEMxaIxcHCAfUfaeaB+jPSAcMwkY6vkifuyVTrc=
    - secure: NX2hryZZZr6jks3+4GSeNDWmyjYp+/+CJxauqUvJhrj0LxrCpr9t+G81ubqNVDw/nJxEZPY6cs5fsryFHLFeZapwbhzjWwpHDVaGZJgW29NGfTJ8oVkYIvnSbUrc3sCQM5XWRro8ECP6+mrd4LYUQ2mnKbTmf/mKg+vT6WkVhsM=
    - secure: euuz/klng7lIEcVzVaXTaXxCEpXbPSqXMcXj59OXYWrgg8imy/nX/fG6a8EDbJ3Y9qnwfkHO0v80OuWVQ2PypNEvS+szNqKx/zDzg9UpU6tWwRUTMqfeSIbvUsl5ecj6TkwCpPKTnp+hVk7+wTZS5UhhPOuK1U4LvtJNuGCmAKI=
addons:
  sauce_connect: true

deploy:
  provider: npm
  email: i59naga@icloud.com
  api_key:
    secure: jsGg/E+2O9xidgeOkBdMyzSMXgkjzfRQCDqWTyNm/YKoat/T42scv5GQIqFkfwRog3Yid7rLo5gKx3S3jdhG23yJ06z1Fyzcp2kjWglgpm/E2Jfe5kHQzwvBxh9NOPs26JMhOiLCYgCDtmppU4frhJiBxtvnaod7G4MWyM6xdhQ=