# Quick boot options
sudo: false
cache:
  directories:
    - node_modules

# Language options
language: node_js
node_js:
  - '0.10'

# COVERALLS_REPO_TOKEN
env:
  global:
    - secure: HmsnQqfaOjZ6HJfursQUvqVRlUN2H1ICwDZXJH6rqSgZi2olA6NT5CCitUG1V+4ksMBIpgT/ELR38OQN82BfWzFIQxLph5BcNYtOcKv+TU49m94hkfB4PXXbM1PhfJlHvuCMqEMxaIxcHCAfUfaeaB+jPSAcMwkY6vkifuyVTrc=

# Npm publish options
before_deploy:
  - npm install coffee-script --global
  - export TRAVIS_BUILD_PASSED=true
deploy:
  provider: npm
  email: i59naga@icloud.com
  api_key:
    secure: jsGg/E+2O9xidgeOkBdMyzSMXgkjzfRQCDqWTyNm/YKoat/T42scv5GQIqFkfwRog3Yid7rLo5gKx3S3jdhG23yJ06z1Fyzcp2kjWglgpm/E2Jfe5kHQzwvBxh9NOPs26JMhOiLCYgCDtmppU4frhJiBxtvnaod7G4MWyM6xdhQ=